name: Build & Release Windows EXE

on:
  push:
    tags:
      - "v*.*.*" # Runs when pushing a version tag like v1.0.0
  workflow_dispatch:

permissions:
  contents: write # Allow release creation
  actions: read

jobs:
  build:
    runs-on: windows-latest #dfghjkl

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --name AirBeam `
            --add-data "airbeam/static;static" `
            --add-data "airbeam/templates;templates" `
            airbeam/main.py

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/AirBeam.exe # Upload EXE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
